Project_PE/Project/myapp/urls.py
from django.urls import path
from .views import *

app_name="myapp"

urlpatterns=[
	path("",MyView.as_view(),name="Home"),
	path("playlist/",MyPlaylistView.as_view(),name="playlist"),
	path('login/',LoginView.as_view(),name="login"),
    path('signup/',SignupView.as_view(),name="signup"),
    path('logout/',LogoutView.as_view(),name="logout"),
    path('api/',addplaylist_api.as_view(),name="add"),
    path('create/',createplaylist_api.as_view(),name="create"),
    path('api/remove/',removeplaylist_api.as_view(),name="remove"),
]

Project_PE/Project/myproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("myapp.urls"))
]

Project_PE/Project/myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,PermissionsMixin,BaseUserManager
from django.utils.translation import ugettext_lazy as _
import uuid

class MyUserManager(BaseUserManager):
    def create_user(self,full_name,phonenumber,email,password=None,admin=False,active=False):
        if not full_name:
            raise ValueError(_("Please Enter Full Name !."))
        if not phonenumber:
            raise ValueError(_("Please Enter Mobile Number !."))
        if not email:
            raise ValueError(_("Please Enter Email !."))
        if not password:
            raise ValueError(_("Please Enter Password !."))
        user=self.model(email=self.normalize_email(email),
                        full_name=full_name,
                        phonenumber=phonenumber,
                        admin=admin,
                        active=active,
                        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_superuser(self,full_name,phonenumber,email,password=None,admin=True,active=True):
        user=self.create_user(full_name,phonenumber,email,password,admin,active)
        user.save(using=self._db)
        return user
    
   




class User(AbstractBaseUser,PermissionsMixin):
    full_name=models.CharField(max_length=255,verbose_name="Full Name")
    email=models.EmailField(unique=True,max_length=255,verbose_name="Email")
    phonenumber=models.CharField(max_length=255,verbose_name="Mobile Number",unique=True)
    admin=models.BooleanField(default=False)
    active=models.BooleanField(default=False)
    date_joined=models.DateTimeField(auto_now_add=True)
  

    USERNAME_FIELD='phonenumber'
    REQUIRED_FIELDS=['full_name','email']
    objects=MyUserManager()

    def __str__(self):
        return str(self.phonenumber)
    
    def is_active(self):
        return self.active

    def is_staff(self):
        return self.admin
    
    def is_admin(self):
        return self.admin

    def is_superuser(self):
        return self.admin
    
    def has_perm(self,perm,obj=None):
        return True
        
    def has_perms(self,perm,obj=None):
        return True

    def has_module_perms(self,app_label):
        return True




class Playlist(models.Model):
    id=models.UUIDField(primary_key=True,editable=False,default=uuid.uuid4)    
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    title=models.CharField(max_length=250,unique=True)
    status=models.BooleanField(default=True)


class Movie(models.Model):
    playlist=models.ForeignKey(Playlist,on_delete=models.CASCADE)
    title=models.CharField(max_length=250)
    img=models.CharField(max_length=250)
    imdb=models.CharField(max_length=250)


    





Project_PE/Project/myapp/forms.py
# accounts.forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import User
from django.contrib.auth import authenticate

class LoginForm(forms.Form):
    phonenumber=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['phonenumber'].widget.attrs['class'] ='input'
        self.fields['phonenumber'].widget.attrs['placeholder'] ='Phonenumber'
        self.fields['password'].widget.attrs['class'] ='input'
        self.fields['password'].widget.attrs['placeholder']='Password'
        self.fields['password'].widget.attrs['id']='password'
    
    def clean_phonenumber(self):
        phone=self.cleaned_data.get('phonenumber',False)
        if(phone and len(str(phone))==10 and phone.isnumeric()):
            try:
                User.objects.get(phonenumber=phone)
            except:
                raise forms.ValidationError("Mobile Number Not Registered.!")
        else:
            raise forms.ValidationError("Please Enter Valid Mobile Number .!")
        return phone
    
    def clean_password(self):
        password=self.cleaned_data.get('password',False)
        if(password and len(password)>1):
            pass
        else:
            raise forms.ValidationError("Please Enter Password Correctly .!")
        return password

    def clean(self):
        cleaned_data=super().clean()
        phonenumber_=cleaned_data.get('phonenumber',None)
        password_=cleaned_data.get('password',None)
        if phonenumber_ and password_:
            pass
        else:
            raise forms.ValidationError("Please Enter Valid Details .!")




    

class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email','full_name','phonenumber')
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['full_name'].widget.attrs['placeholder'] = 'Full Name'
        self.fields['full_name'].widget.attrs['id'] = 'full_name'
        self.fields['phonenumber'].widget.attrs['placeholder'] = 'Phone Number'
        self.fields['phonenumber'].widget.attrs['id'] = 'phonenumber'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['email'].widget.attrs['id'] = 'email'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password1'].widget.attrs['id'] = 'password1'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['password2'].widget.attrs['id'] = 'password2'
    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("Email is already taken .!")
        return email
    
    def clean_phonenumber(self):
        phonenumber = self.cleaned_data.get('phonenumber')
        if(len(str(phonenumber)) != 10):
            raise forms.ValidationError("Enter Valid Phonenumber .!") 
        qs = User.objects.filter(phonenumber=phonenumber)
        if qs.exists():
            raise forms.ValidationError("Phonenumber is Already taken .!")
        return phonenumber

    def clean_password1(self):
        password1 = self.cleaned_data.get("password1")
        if not password1 or len(str(password1))<5:
            raise forms.ValidationError("Enter Valid Password.!")
        return password1

    def clean_password2(self):
        password2 = self.cleaned_data.get("password2")
        if not password2 or len(str(password2))<5:
            raise forms.ValidationError("Enter Valid Password.!")
        return password2
    
    
    def clean(self):
        cleaned_data=super().clean()
        password2 = self.cleaned_data.get("password2")
        password1 = self.cleaned_data.get("password1")
        if(password1 and password2):
            if(password1!=password2):
                raise forms.ValidationError("Password Not Matched .!")
        else:
            raise forms.ValidationError("Enter Passwrods .!")


class UserAdminCreationForm(forms.ModelForm):

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email','full_name','phonenumber','admin')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.active=True
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email','full_name','phonenumber', 'password', 'active', 'admin')

    def clean_password(self):
        return self.initial["password"]

Project_PE/Project/myapp/views.py
from django.shortcuts import render,redirect
from django.views.generic import View,RedirectView
from .forms import LoginForm,RegisterForm
from django.contrib.auth import authenticate,login,logout
from .models import User,Playlist,Movie
from rest_framework.views import APIView
from rest_framework import serializers
from rest_framework.response import Response



class MyView(View):

	def get(self,request):
		if(not request.user.is_authenticated):
			return redirect("myapp:login")
		return render(request,'myapp/index.html',{"playlists":Playlist.objects.filter(user=request.user)})

class MyPlaylistView(View):

    def get(self,request):
        try:
            playlist=Playlist.objects.get(id=request.GET.get('id'))
        except:
            pass
        if playlist.status:
            if request.user.is_authenticated:
                return render(request,'myapp/playlist.html',{"movies":Movie.objects.filter(playlist=playlist),"playlist":playlist.title,"status":True})
            else:
                return render(request,'myapp/playlist.html',{"movies":Movie.objects.filter(playlist=playlist),"playlist":playlist.title,"status":False})
        if(not request.user.is_authenticated):
            return redirect("myapp:login")
        return render(request,'myapp/playlist.html',{"movies":Movie.objects.filter(playlist=playlist),"playlist":playlist.title,"status":True})



class LoginView(View):
    def get(self,request):
        return render(request,'myapp/login.html',{"form":LoginForm()})
    
    def post(self,request):
        context={}
        error=False
        try:
            form=LoginForm(request.POST)
            if(form.is_valid()):
                phonenumber=form.cleaned_data['phonenumber']
                password=form.cleaned_data['password']
                print(phonenumber,password)
                log=authenticate(request,phonenumber=phonenumber,password=password)
                if(log is not None):
                    login(request,log,backend='django.contrib.auth.backends.ModelBackend')
                    return redirect("myapp:Home")
                else:
                    error="Enter Valid Details.!"
            else:
                try:
                    error=list(form.errors.values())[0][0]
                except:
                    error="Try Again with Valid Details"
            context['form']=form
        except Exception as err:
            error=err
        context['error']=error
        return render(request,'myapp/login.html',context)    




class SignupView(View):

    def get(self,request):
    	return render(request,'myapp/signup.html',{"form":RegisterForm()})
    
    def post(self,request):
        context={}
        error=False
        try:
            form=RegisterForm(request.POST)
            if(form.is_valid()):
                full_name=form.cleaned_data.get('full_name')
                phonenumber=form.cleaned_data.get('phonenumber')
                email=form.cleaned_data.get('email')
                password1=form.cleaned_data.get('password1')
                password2=form.cleaned_data.get('password2')
                if(password1==password2):
                    try:
                        User.objects.create_user(full_name=full_name,phonenumber=phonenumber,email=email,password=password2)
                        return redirect("myapp:login")
                    except:
                        error="Try again with Valid details"
                else:
                    error="Passwords Not Matched"
            else:
                error=list(form.errors.values())[0][0]
            context['form']=form
        except Exception as err:
            error=err
        context['error']=error
        return render(request,'myapp/signup.html',context)


class LogoutView(RedirectView):
    url = '/login/'
    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)




class addplaylist_api(APIView):

    @staticmethod
    def get(request):
        img=request.GET.get('image')
        title=request.GET.get('title')
        imdb=request.GET.get('imdb') 
        playlist=request.GET.get('playlist')
        if playlist=="None":
            return Response({"status":False,"message":"Please Select Playlist"})
        try:
            playlist=Playlist.objects.get(title=playlist,user=request.user)
        except:
            return Response({"status":False,"message":"Playlist not found"})
        if(Movie.objects.filter(title=title,playlist=playlist).count()==0):
            Movie.objects.create(playlist=playlist,title=title,img=img,imdb=imdb)
        else:
            return Response({"status":False,"message":"Movie already in list"})
        return Response({"status":True})


class createplaylist_api(APIView):

    @staticmethod
    def get(request):
        title=request.GET.get('title')
        status=request.GET.get('status')
        print(status)
        if(Playlist.objects.filter(title=title,user=request.user).count()==0):
            Playlist.objects.create(user=request.user,title=title,status=True if status=="public" else 0)
        else:
            return Response({"status":False,"message":"Playlist already in list"})
        return Response({"status":True})

class removeplaylist_api(APIView):

    @staticmethod
    def get(request):
        imdb=request.GET.get('imdb') 
        playlist=request.GET.get('playlist')
        try:
            playlist=Playlist.objects.get(title=playlist,user=request.user)
        except:
            return Response({"status":False,"message":"Playlist not found"})
        if(Movie.objects.filter(imdb=imdb,playlist=playlist).count()):
            Movie.objects.filter(imdb=imdb,playlist=playlist).delete()
        return Response({"status":True})

    

Project_PE/Project/myapp/templates/myapp/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Simple login form</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/home.css' %}">
    <script src="https://code.jquery.com/jquery-latest.js"></script>
    <style type="text/css">
    .pseduo-track {
      background-color: white;
      height: 2px;
      width: 100%;
      position: relative;
      top: -3px;
      z-index: -10;
    }

    @media (any-hover: none) {
      .pseduo-track {
        display: none;
      }
    }

    .outer-wrapper::-webkit-scrollbar {
      height: 5px;
    }

    .outer-wrapper::-webkit-scrollbar-track {
      -webkit-box-shadow: inset 0 0 0px rgba(0, 0, 0, 0);
    }

    .outer-wrapper::-webkit-scrollbar-thumb {
      height: 5px;
      /*scroll color*/
      background-color: #24B586;
    }

    .outer-wrapper::-webkit-scrollbar-thumb:hover {
      background-color: #f1db9d;
    }

    .outer-wrapper::-webkit-scrollbar:vertical {
      display: none;
    }
    .outer-wrapper h1{
      margin:10px;
      color:var(--primary);
    }

    .outer-wrapper {
      max-width: 100vw;
      overflow-x: scroll;
      position: relative;
      scrollbar-width: thin;
      -ms-overflow-style: none;
    }

    .inner-wrapper {
      display: flex;
      padding-bottom: 10px;
    }
    .pseudo-item {
      height: 200px;
      width: 300px;
      margin-right: 30px;
      flex-shrink: 0;
      background-color: gray;
      display: flex;
      flex-flow: column;
      justify-content: space-around;
      align-items: center;
      border-radius:20px;
    }
  </style>
  </head>
  <body id="main_container">
    <header class="showcase">  
        <div class="showcase-top">  
             <img src="https://i.ibb.co/r5krrdz/logo.png" alt="" />  
             <a href="/logout" class="btn btn-rounded">Sign out</a>  
             <!-- <a href="/playlist" class="btn btn-rounded playlist">My PlayList</a>   -->
        </div>  
        <div class="showcase-content">  
             <h1>See what's next</h1>  
             <p>Watch anywhere. Create Your Playlist</p>
             <div class="wrap"> 
               <div class="search">
                    <input type="text" id="movie" class="searchTerm" placeholder="What are you looking for?" autofocus>
                    <button type="submit" id="btnAdd" class="searchButton" onclick="get_value()">
                      <i class="fa fa-search"></i>
                   </button>
                 </div>
              </div> 
        </div>  
    </header>  
    <section>
      <div class="outer-wrapper">
        <div style="display: flex;justify-content: space-between; margin:10px;">
          <div><h1>PlayLists</h1></div>
          <div><button class="btn" onclick="create_playlist();">Create New PlayList</button></div>
        </div>
        <div class="inner-wrapper">
          {% for i in playlists %}
          <div class="pseudo-item">
            <div><h2>{{i.title}}</h2></div>
            {% if i.status %}
            <div><h3>Public</h3></div>
            {% else %}
            <div><h3>Private</h3></div>
            {% endif %}
            <div><a href="/playlist?id={{i.id}}">Open</a></div>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="pseduo-track"></div>
    </section>
   <div class="wrapper" id="wrapper">
   </div>

    <div class="form-popup" id="myForm">
    <form class="form-container" onsubmit="return false;">
      <!-- <label for="email"><b>Select PlayList</b></label> -->
      <input type="hidden" id="image">
      <input type="hidden" id="title">
      <input type="hidden" id="imdb">
      <select class="custom-select" id="playlist" autofocus>
        <option value="None">Select Playlist</option>
        {% for i in playlists %}
        <option value="{{i.title}}">{{i.title}}</option>
        {% endfor %}
      </select>
      <button type="submit" class="btn" onclick="addPlaylist();">Submit</button>
      <button type="button" class="btn cancel" onclick="closeForm()">Close</button>
    </form>
    </div>

    <div class="form-popup" id="myForm2">
    <form class="form-container" onsubmit="return false;">
      <label for="play"><b>Playlist Name</b></label> 
      <input type="text" placeholder="Enter playlist" id="play" required>
      <div class="form-group">
        <input id="private" type="radio" name="custom-radio-btn" value="private" required>
        <label class="custom-radio" for="private"></label>
        <span class="label-text">Private</span>
      </div>
      <div class="form-group">
        <input id="public" type="radio" name="custom-radio-btn" value="public" required>
        <label class="custom-radio" for="public"></label>
        <span class="label-text">Public</span>
      </div>
      <button type="submit" class="btn" onclick="createPlaylist()">Submit</button>
      <button type="button" class="btn cancel" onclick="closeForm2()">Close</button>
    </form>
    </div>



    <footer class="footer">  
      <p>Questions? Call 1-866-579-7172</p>  
      <div class="footer-cols">  
           <ul>  
                <li><a href="#">FAQ</a></li>  
                <li><a href="#">Investor Relations</a></li>  
                <li><a href="#">Ways To Watch</a></li>  
                <li><a href="#">Corporate Information</a></li>  
                <li><a href="#">Netflix Originals</a></li>  
           </ul>  
           <ul>  
                <li><a href="#">Help Center</a></li>  
                <li><a href="#">Jobs</a></li>  
                <li><a href="#">Terms Of Use</a></li>  
                <li><a href="#">Contact Us</a></li>  
           </ul>  
           <ul>  
                <li><a href="#">Account</a></li>  
                <li><a href="#">Redeem Gift Cards</a></li>  
                <li><a href="#">Privacy</a></li>  
                <li><a href="#">Speed Test</a></li>  
           </ul>  
           <ul>  
                <li><a href="#">Media Center</a></li>  
                <li><a href="#">Buy Gift Cards</a></li>  
                <li><a href="#">Cookie Preferences</a></li>  
                <li><a href="#">Legal Notices</a></li>  
           </ul>  
      </div>  
    </footer>  
  </body>
</html>


<script src="http://code.jquery.com/jquery-1.11.2.min.js"></script> 

<script type="text/javascript">
  function get_value(){
      var movie=document.getElementById("movie").value;
      var final="";
      $.ajax({
        url:"http://www.omdbapi.com/?apikey=169ed9b7&s=".concat(movie),
        dataType:'json',
        success: function(data){
          if(data.Response=="True"){
            for (i in data.Search){
              let poster=data.Search[i].Poster;
              if(poster=="N/A"){
                poster="https://thumbs.dreamstime.com/z/no-image-available-icon-flat-vector-no-image-available-icon-flat-vector-illustration-132482953.jpg"
              }
              final=final.concat(`<div class="movie-card"><div class="movie-img"><img src="${poster}"></div><div class="card-body"><p class="movie-title">${data.Search[i].Title}</p><p class="movie-intro">IMDB ID :${data.Search[i].imdbID}</p><button onclick="add_to_playlist('${poster}','${data.Search[i].Title}','${data.Search[i].imdbID}')">Add to Playlist</button></div></div>`)
            }
            $(function () {
                // var div = $("<div>");
                // div.html(final);
                $("#wrapper").append(final);
            });
          }
          else{
            final=final.concat('<center>'+data.Error+'</center>')
          }
        },
      })
      return final;
    }

    var updates=document.getElementsByClassName('add_update');
    for (i=0;i<updates.length;i++){
      updates[i].addEventListener('click',function(){
        add_to_playlist(this.dataset.image,this.dataset.title,this.dataset.imdb);
      })
    }

    function create_playlist(){
      document.getElementById("myForm2").style.display = "block";      
    }

    function add_to_playlist(image,title,imdb){
      var containerElement = document.getElementById('main_container');
      containerElement.setAttribute('class', 'blur');
      document.getElementById("myForm").style.display = "block";
      document.getElementById("image").value=image;
      document.getElementById("title").value=title;
      document.getElementById("imdb").value=imdb;
    }
    function addPlaylist(){
      $.ajax({
        url:"{% url 'myapp:add' %}",
        dataType:'json',
        data:{
            "image":document.getElementById("image").value,
            "title":document.getElementById("title").value,
            "imdb":document.getElementById("imdb").value,
            "playlist":document.getElementById("playlist").value
          },
        success: function(data){
          if(data.status){
            alert("Added successfully");
          }
          else{
            alert(data.message);
          }
        },
      })
      closeForm();
    }

    function createPlaylist(){
      $.ajax({
        url:"{% url 'myapp:create' %}",
        dataType:'json',
        data:{
            "status":document.querySelector('input[name="custom-radio-btn"]:checked').value,
            "title":document.getElementById("play").value,
          },
        success: function(data){
          if(data.status){
            alert("Added successfully");
            location.reload();
          }
          else{
            alert(data.message);
          }
        },
      })
      closeForm2();
    }
    function closeForm() {
      document.getElementById("myForm").style.display = "none";
    }
     function closeForm2() {
      document.getElementById("myForm2").style.display = "none";
    }
</script>

Project_PE/Project/myapp/templates/myapp/login.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en" >
<html>
<head>
  <title>Login</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="{% static 'myapp/login_style.css' %}">
</head>

<body class="body">
	
<div class="login-page">
  <div class="form">

    <form method="POST" action=".">
      <center> <h1>Login</h1></center>
      {% csrf_token %}
        {% if error %}
          <p id="messages" style="color:red;">{{error}}</p>
        {% endif %}
      {{form.phonenumber}}
      {{form.password}}
      <br>
      <button>LOGIN</button>
      <p class="message"></p>
    </form>

    <form class="login-form">
      <button type="button" onclick="window.location.href='/signup/'">SIGN UP</button>
    </form>
  </div>
</div>
</body>
</html>

Project_PE/Project/myapp/templates/myapp/playlist.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Simple login form</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/playlist.css' %}">
    <script src="https://code.jquery.com/jquery-latest.js"></script>
  </head>
  <body>
    <header class="showcase">  
        <div class="showcase-top">  
             <img src="https://i.ibb.co/r5krrdz/logo.png" alt="" />
             {% if status %} 
             <a href="/logout" class="btn btn-rounded">Sign out</a>
             {% endif %}  
             <a href="/" class="btn btn-rounded playlist">Home</a>  
        </div> 
    </header>
    <div class="wrapper">
      {% for i in movies %}
          <div class="movie-card">
            <div class="movie-img">
              <img src="{{i.img}}">
            </div>
            <div class="card-body">
              <p class="movie-title">{{i.title}}</p>
              <p class="movie-intro">IMDB ID :{{i.imdb}}</p>
              {% if status %}
              <button onclick="myfunc('{{i.imdb}}','{{playlist}}')">Remove</button>
              {% endif %}
            </div>
          </div>
          {% endfor %}
   </div>  
    <footer class="footer">  
      <p>Questions? Call 1-866-579-7172</p>  
      <div class="footer-cols">  
           <ul>  
                <li><a href="#">FAQ</a></li>  
                <li><a href="#">Investor Relations</a></li>  
                <li><a href="#">Ways To Watch</a></li>  
                <li><a href="#">Corporate Information</a></li>  
                <li><a href="#">Netflix Originals</a></li>  
           </ul>  
           <ul>  
                <li><a href="#">Help Center</a></li>  
                <li><a href="#">Jobs</a></li>  
                <li><a href="#">Terms Of Use</a></li>  
                <li><a href="#">Contact Us</a></li>  
           </ul>  
           <ul>  
                <li><a href="#">Account</a></li>  
                <li><a href="#">Redeem Gift Cards</a></li>  
                <li><a href="#">Privacy</a></li>  
                <li><a href="#">Speed Test</a></li>  
           </ul>  
           <ul>  
                <li><a href="#">Media Center</a></li>  
                <li><a href="#">Buy Gift Cards</a></li>  
                <li><a href="#">Cookie Preferences</a></li>  
                <li><a href="#">Legal Notices</a></li>  
           </ul>  
      </div>  
    </footer>  
  </body>
</html>
<script src="http://code.jquery.com/jquery-1.11.2.min.js"></script> 

<script type="text/javascript">
   function myfunc(imdb,playlist){
      $.ajax({
        url:"{% url 'myapp:remove' %}",
        dataType:'json',
        data:{"imdb":imdb,"playlist":playlist},
        success: function(data){
          if(data.status){
            alert("Removed successfully");
            location.reload();
          }
        },
      })
    }
</script>

Project_PE/Project/myapp/templates/myapp/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <html>
    <head>
      <title>Sign Up</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta charset="utf-8" />
      <link rel="stylesheet" type="text/css" href="{% static 'myapp/signup_style.css' %}" />
    </head>

    <body class="body">

      <div class="login-page">
        <div class="form">
          <form method="POST" action=".">
            <center><h1>Signup</h1></center>
            {% csrf_token %}
            {% if error %}
                <p style="margin-top:30px;margin-left:30px;color:red;">{{error}}</p>
            {% endif %}
            {{form.full_name}}
            {{form.phonenumber}}
            {{form.email}}
            {{form.password1}}
            {{form.password2}}
            <br>
            <button>
              SIGN UP
            </button>
          </form>
           <button type="button" onclick="window.location.href='/login/'">
              Login
          </button>
        </div>
      </div>
    </body>
   
  </html>
</html>

<script type="text/javascript">
   function myfunc(imdb){
      $.ajax({
        url:"{% url 'myapp:remove' %}",
        dataType:'json',
        data:{"imdb":imdb},
        success: function(data){
          if(data.status){
            alert("Removed successfully");
            location.reload();
          }
        },
      })
    }
</script>